# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"


gem "parallel", "~> 1.12"

gem "ruby-progressbar", "~> 1.10"
